### ISSUE TITLE
Build is not working

### ISSUE THREAD

**Issue by MikeAlhayek** [fluffynuts/gulp-msbuild#4]
Hi, I am trying to write a gulp task that would clean then build my asp.net MVC 5/C# solution.

Here is the gulp task
```
function releaseService(cb) {
    cb();

    return gulp.src('../*.sln')
        .pipe(msbuild({
            toolsVersion: 14.0,
            properties: {
                Configuration: 'Release'
            },
            targets: ['Clean', 'Build'],
            errorOnFail: true,
            stdout: true
        }));
}
```

But I get `MSBuild failed!` I am not sure what I am doing wrong here. Below is the top portion of the output. How can I build my solution using `gulp-msbuild`?

```
Error: spawn C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\amd64\\MSBuild.exe',
  path: 'C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\amd64\\MSBuild.exe',
  spawnargs: [
    'Path_To_My_Solution.sln',
    '/target:Clean;Build',
    '/verbosity:normal',
    '/toolsversion:14.0',
    '/nologo',
    '/maxcpucount',
    '/property:Configuration=Release'
  ]
}
MSBuild failed!
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe ENOENT
←[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)←[39m
←[90m    at onErrorNT (internal/child_process.js:469:16)←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:84:21)←[39m
Emitted 'error' event on Domain instance at:
←[90m    at PassThrough.EventEmitter.emit (domain.js:500:12)←[39m
```

The solution should build with no issues as I am able to build my solution using Visual Studio 2017 with no problem.

**Comment by MikeAlhayek** [comment]
I figured it out. The location of the `msbuild.exe` was invalid.

I changed my task to the following and it worked

function releaseService(cb) {
    cb();

    return gulp.src('../*.sln')
        .pipe(msbuild({
            toolsVersion: 'auto',
            properties: {
                Configuration: 'Release',
                VisualStudioVersion: '15.0'
            },
            targets: ['Clean', 'Build'],
            errorOnFail: true,
            stdout: true
        }));
}
